### ISSUE TITLE
[stack-ibm-core-security-services] Expose the ability to enable SM engines

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/stack-ibm-core-security-services#59]
SM DA has the ability to enable the different engines. These should be exposed at the stack level

**Comment by ocofaigh** [comment]
Re-opening to track adding other engines

**Comment by iamar7** [comment]
As per this [suggestion](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/pull/100#issuecomment-2352703877), created an issue https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/148 to add the documentation for enabling public/private cert engine. Closing this issue since there is no code changes required in the repo.
